name: CI
on:
  pull_request_target:
    types:
      - labeled
      - opened
      - synchronize
      - reopened
    branches:
      - main

jobs:
  authorize:
    environment:
      ${{ github.event_name == 'pull_request_target' &&
      github.event.pull_request.head.repo.full_name != github.repository &&
      'external' || 'internal' }}
    runs-on: ubuntu-latest
    steps:
      - run: true
  external_job:
    needs: authorize  # Ensures it runs after authorize
    runs-on: ubuntu-latest
    steps:
      - name: Execute external job
        run: echo "Running external job environment is external"
