name: CI
on:
  pull_request_target:
    types:
      - labeled
      - opened
      - synchronize
      - reopened
    branches:
      - main

jobs:
  authorize:
    environment:
      ${{ github.event_name == 'pull_request_target' &&
      'external' || 'internal' }}
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ github.token }}
      repository: ${{ github.repository  }}
      run_id: ${{ github.run_id }}
    steps:
      - name: Get Testing Configuration
        run: |
          config_file=test
          config=$(gh api "/repos/$repository/actions/runs/$run_id/approvals" --jq '.[0] | .comment')
          if [[ -n "$config" ]]; then
            echo "Testing configuration was overwritten"
            echo "$config" > test_new_file
            echo "Running cat"
            cat test_new_file
          else
            echo "Default testing configuration"
          fi
  external_job:
    needs: authorize
    runs-on: ubuntu-latest
    steps:
      - name: Execute external job
        run: |
          echo "Running cat"
          echo cat test_new_file
          cat test_new_file
          echo "Running external job environment is external"
